onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@reown/appkit'
  - '@tailwindcss/oxide'
  - bufferutil
  - esbuild
  - keccak
  - prisma
  - secp256k1
  - sharp
  - utf-8-validate
